<table width="100%" border="0" cellpadding="0" cellspacing="0" id="f_nota_medica"><tr><td>PACIENTE: {et_nombre_paciente}</td><td>{et_sex} DE {et_edad}</td></tr><tr><td>NOTA MÉDICA</td><td>MÉDICO: {et_nombre_personal_atiende}</td></tr><tr><td colspan="2" align="right" style="font-size:10px;">MUNICIPIO, EDO. A {et_fecha_dia} DE {et_fecha_mes} DE {et_fecha_anio}</td></tr><tr><td valign="top" height="650px" colspan="2" align="" style="" id="espacio_notam"><br><br></td></tr><tr><td colspan="2" align="" style="" id=""><br><br><br><br></td></tr><tr><td colspan="2" align="center" style="" id="">{et_nombre_personal_atiende}</td></tr><tr><td colspan="2" align="center" style="" id="">CÉDULA PROFESIONAL {et_cedulap}</td></tr></table>

<table width="100%" border="0" cellpadding="0" cellspacing="0" id="f_receta_medica"><tr><td>PACIENTE: {et_nombre_paciente}</td><td>{et_sex} DE {et_edad}</td></tr><tr><td>RECETA MÉDICA</td><td>MÉDICO: {et_nombre_personal_atiende}</td></tr><tr><td colspan="2" align="right" style="font-size:10px;">MUNICIPIO, EDO. A {et_fecha_dia} DE {et_fecha_mes} DE {et_fecha_anio}</td></tr><tr><td valign="top" height="650px" colspan="2" align="" style="" id="espacio_notam1"><br><br></td></tr><tr><td colspan="2" align="" style="" id=""><br><br><br><br></td></tr><tr><td colspan="2" align="center" style="" id="">{et_nombre_personal_atiende}</td></tr><tr><td colspan="2" align="center" style="" id="">CÉDULA PROFESIONAL {et_cedulap}</td></tr></table>

<table width="100%" border="0" cellpadding="0" cellspacing="0" id="f_estudio_lab"><tr><td>PACIENTE: {et_nombre_paciente}</td><td>{et_sex} DE {et_edad}</td></tr><tr><td>{et_nombre_procedimiento}</td><td>REFIERE: {et_nombre_personal_atiende}</td></tr><tr><td colspan="2" align="right" style="font-size:10px;">MUNICIPIO, EDO. A {et_fecha_dia} DE {et_fecha_mes} DE {et_fecha_anio}</td></tr><tr><td valign="top" height="650px" colspan="2" align="" style="" id="espacio_notam2"><br><br></td></tr><tr><td colspan="2" align="" style="" id=""><br><br><br><br></td></tr><tr><td colspan="2" align="center" style="" id="">{et_nombre_personal_atiende}</td></tr><tr><td colspan="2" align="center" style="" id="">CÉDULA PROFESIONAL {et_cedulap}</td></tr></table>

<table width="100%" border="0" cellpadding="0" cellspacing="0" id="f_estudio_img"><tr><td>PACIENTE: {et_nombre_paciente}</td><td>{et_sex} DE {et_edad}</td></tr><tr><td>{et_nombre_procedimiento}</td><td>REFIERE: {et_nombre_personal_atiende}</td></tr><tr><td colspan="2" align="right" style="font-size:10px;">MUNICIPIO, EDO. A {et_fecha_dia} DE {et_fecha_mes} DE {et_fecha_anio}</td></tr><tr><td valign="top" height="650px" colspan="2" align="" style="" id="espacio_notam3"><br><br></td></tr><tr><td colspan="2" align="" style="" id=""><br><br><br><br></td></tr><tr><td colspan="2" align="center" style="" id="">{et_nombre_personal_atiende}</td></tr><tr><td colspan="2" align="center" style="" id="">CÉDULA PROFESIONAL {et_cedulap}</td></tr></table>

<table width="100%" border="0" cellpadding="0" cellspacing="0" id="f_estudio_endo"><tr><td>PACIENTE: {et_nombre_paciente}</td><td>{et_sex} DE {et_edad}</td></tr><tr><td>{et_nombre_procedimiento}</td><td>REFIERE: {et_nombre_personal_atiende}</td></tr><tr><td colspan="2" align="right" style="font-size:10px;">MUNICIPIO, EDO. A {et_fecha_dia} DE {et_fecha_mes} DE {et_fecha_anio}</td></tr><tr><td valign="top" height="650px" colspan="2" align="" style="" id="espacio_notam4"><br><br></td></tr><tr><td colspan="2" align="" style="" id=""><br><br><br><br></td></tr><tr><td colspan="2" align="center" style="" id="">{et_nombre_personal_atiende}</td></tr><tr><td colspan="2" align="center" style="" id="">CÉDULA PROFESIONAL {et_cedulap}</td></tr></table>

<table width="100%" border="0" cellpadding="0" cellspacing="0" id="f_estudio_ultra"><tr><td>PACIENTE: {et_nombre_paciente}</td><td>{et_sex} DE {et_edad}</td></tr><tr><td>{et_nombre_procedimiento}</td><td>REFIERE: {et_nombre_personal_atiende}</td></tr><tr><td colspan="2" align="right" style="font-size:10px;">MUNICIPIO, EDO. A {et_fecha_dia} DE {et_fecha_mes} DE {et_fecha_anio}</td></tr><tr><td valign="top" height="650px" colspan="2" align="" style="" id="espacio_notam5"><br><br></td></tr><tr><td colspan="2" align="" style="" id=""><br><br><br><br></td></tr><tr><td colspan="2" align="center" style="" id="">{et_nombre_personal_atiende}</td></tr><tr><td colspan="2" align="center" style="" id="">CÉDULA PROFESIONAL {et_cedulap}</td></tr></table>

<table width="100%" border="0" cellpadding="0" cellspacing="0" id="f_estudio_colpo"><tr><td>PACIENTE: {et_nombre_paciente}</td><td>{et_sex} DE {et_edad}</td></tr><tr><td>{et_nombre_procedimiento}</td><td>REFIERE: {et_nombre_personal_atiende}</td></tr><tr><td colspan="2" align="right" style="font-size:10px;">MUNICIPIO, EDO. A {et_fecha_dia} DE {et_fecha_mes} DE {et_fecha_anio}</td></tr><tr><td valign="top" height="650px" colspan="2" align="" style="" id="espacio_notam6"><br><br></td></tr><tr><td colspan="2" align="" style="" id=""><br><br><br><br></td></tr><tr><td colspan="2" align="center" style="" id="">{et_nombre_personal_atiende}</td></tr><tr><td colspan="2" align="center" style="" id="">CÉDULA PROFESIONAL {et_cedulap}</td></tr></table>

<table width="100%" border="0" cellpadding="0" cellspacing="0" id="f_servicios"><tr><td>PACIENTE: {et_nombre_paciente}</td><td>{et_sex} DE {et_edad}</td></tr><tr><td>{et_nombre_procedimiento}</td><td>REFIERE: {et_nombre_personal_atiende}</td></tr><tr><td colspan="2" align="right" style="font-size:10px;">MUNICIPIO, EDO. A {et_fecha_dia} DE {et_fecha_mes} DE {et_fecha_anio}</td></tr><tr><td valign="top" height="650px" colspan="2" align="" style="" id="espacio_notam7"><br><br></td></tr><tr><td colspan="2" align="" style="" id=""><br><br><br><br></td></tr><tr><td colspan="2" align="center" style="" id="">{et_nombre_personal_atiende}</td></tr><tr><td colspan="2" align="center" style="" id="">CÉDULA PROFESIONAL {et_cedulap}</td></tr></table>